import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { supabase } from '../lib/supabase';
import { useAuth } from '../context/AuthContext';
import { useCart } from '../context/CartContext';
import './Checkout.css';
const initialForm = { fullName: '', email: '', phone: '', streetAddress: '', city: '', state: '', pinCode: '' };
export default function Checkout() {
  const { cart, cartTotal, clearCart } = useCart(); const { user } = useAuth(); const navigate = useNavigate(); const [formData, setFormData] = useState({ ...initialForm, email: user?.email || '' }); const [error, setError] = useState(''); const [processing, setProcessing] = useState(false); const tax = cartTotal * .18; const delivery = cartTotal ? 99 : 0; const total = cartTotal + tax + delivery;
  const update = (event) => setFormData((current) => ({ ...current, [event.target.name]: event.target.value }));
  const pay = async (event) => { event.preventDefault(); setError(''); if (!cart.length) return setError('Your cart is empty.'); setProcessing(true); try { if (!window.Razorpay) throw new Error('Razorpay is still loading. Please try again.'); const options = { key: import.meta.env.VITE_RAZORPAY_KEY_ID, amount: Math.round(cartTotal * 100), currency: 'INR', name: 'Sai Baba Electronics', description: 'Electronics purchase', prefill: { name: formData.fullName, email: formData.email, contact: formData.phone }, theme: { color: '#0033a0' }, handler: async (response) => { if (!supabase) throw new Error('Order service is unavailable.'); const { data, error: orderError } = await supabase.from('orders').insert({ user_id: user?.id || null, user_email: formData.email, shipping_address: formData, total_amount: cartTotal, payment_status: 'paid', payment_id: response.razorpay_payment_id, items: cart }).select('id').single(); if (orderError) throw orderError; clearCart(); navigate(`/order-success/${data.id}`); } }; new window.Razorpay(options).open(); } catch (paymentError) { setError(paymentError.message || 'Unable to start payment.'); setProcessing(false); } };
  return <main className="checkout-page container"><div className="checkout-heading"><span className="eyebrow">Secure checkout</span><h1>Complete your order</h1></div><div className="checkout-grid"><form className="address-form" onSubmit={pay}><h2>Shipping details</h2><div className="form-grid">{[['fullName','Full Name'],['email','Email'],['phone','Phone'],['streetAddress','Street Address'],['city','City'],['state','State'],['pinCode','PIN Code']].map(([name, label]) => <label key={name} className={name === 'streetAddress' ? 'full-field' : ''}>{label}<input name={name} value={formData[name] || (name === 'email' ? user?.email : name === 'fullName' ? user?.user_metadata?.full_name : '') || ''} onChange={update} type={name === 'email' ? 'email' : name === 'phone' || name === 'pinCode' ? 'tel' : 'text'} required /></label>)}</div>{error && <p className="checkout-error" role="alert">{error}</p>}<button className="btn btn-primary payment-button" disabled={processing}>{processing ? 'Opening payment...' : `Pay ₹${total.toLocaleString('en-IN', { maximumFractionDigits: 0 })}`}</button><small>Payments are processed securely in Razorpay Test Mode.</small></form><aside className="order-summary"><h2>Order summary</h2>{cart.map((item) => <div className="summary-item" key={item.id || item.product_id}><span>{item.title || item.name} x {item.quantity || 1}</span><strong>₹{(Number(item.price || 0) * (item.quantity || 1)).toLocaleString('en-IN')}</strong></div>)}<div className="summary-line"><span>Subtotal</span><strong>₹{cartTotal.toLocaleString('en-IN', { maximumFractionDigits: 0 })}</strong></div><div className="summary-line"><span>Tax</span><strong>₹{tax.toLocaleString('en-IN', { maximumFractionDigits: 0 })}</strong></div><div className="summary-line"><span>Delivery</span><strong>₹{delivery}</strong></div><div className="summary-total"><span>Total</span><strong>₹{total.toLocaleString('en-IN', { maximumFractionDigits: 0 })}</strong></div></aside></div></main>;
}
